services:
  postgres:
    image: postgres:alpine
    container_name: postgres-instance
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-instance
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my-network

  app:
    build: ./
    container_name: app-instance
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data: