basePath: /
definitions:
  domain.CreateRunRequest:
    properties:
      avatar_url:
        type: string
      description:
        type: string
      max_participants:
        type: integer
      name:
        type: string
      official_site_url:
        type: string
      participation_format:
        $ref: '#/definitions/domain.RunParticipationFormat'
      permissions:
        $ref: '#/definitions/domain.RunPermissionsType'
      registration_until:
        type: string
      route:
        $ref: '#/definitions/domain.Route'
      start_place:
        $ref: '#/definitions/domain.Place'
      start_time:
        type: string
      transaction_id:
        type: string
    type: object
  domain.CreateRunResponse:
    properties:
      run:
        $ref: '#/definitions/domain.Run'
    type: object
  domain.ErrorCode:
    enum:
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - CodeUserNameAlreadyTaken
    - CodeWrongPassword
  domain.ErrorResponse:
    properties:
      code:
        $ref: '#/definitions/domain.ErrorCode'
      message:
        type: string
    type: object
  domain.JWTTokenData:
    properties:
      expiresAt:
        type: string
      token:
        type: string
    type: object
  domain.Place:
    properties:
      address:
        type: string
      point:
        $ref: '#/definitions/domain.Point'
    type: object
  domain.Point:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  domain.RefreshTokensRequest:
    properties:
      authToken:
        type: string
      refreshToken:
        type: string
    type: object
  domain.RefreshTokensResponse:
    properties:
      authToken:
        $ref: '#/definitions/domain.JWTTokenData'
      refreshToken:
        type: string
    type: object
  domain.Route:
    properties:
      points:
        items:
          $ref: '#/definitions/domain.Point'
        type: array
    type: object
  domain.Run:
    properties:
      avatar_url:
        type: string
      creator:
        type: integer
      description:
        type: string
      id:
        type: integer
      max_participants:
        type: integer
      name:
        type: string
      official_site_url:
        type: string
      participation_format:
        $ref: '#/definitions/domain.RunParticipationFormat'
      permissions:
        $ref: '#/definitions/domain.RunPermissionsType'
      registration_until:
        type: string
      route:
        $ref: '#/definitions/domain.Route'
      start_place:
        $ref: '#/definitions/domain.Place'
      start_time:
        type: string
      status:
        $ref: '#/definitions/domain.RunStatus'
    type: object
  domain.RunParticipationFormat:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - OpenRunFormat
    - ClosedRunFormat
  domain.RunPermissionsType:
    enum:
    - 0
    type: integer
    x-enum-varnames:
    - FreeRunPermissionsType
  domain.RunStatus:
    enum:
    - 0
    - 1
    - 2
    - 4
    type: integer
    x-enum-varnames:
    - OpenRunStatus
    - RunningRunStatus
    - FinishedRunStatus
    - CanceledRunStatus
  domain.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.SignInResponse:
    properties:
      authToken:
        $ref: '#/definitions/domain.JWTTokenData'
      refreshToken:
        type: string
    type: object
  domain.SignUpRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.SignUpResponse:
    type: object
  domain.SubscriptionRequest:
    properties:
      userId:
        type: integer
    type: object
  domain.SubscriptionResponse:
    type: object
  domain.UpdateRunRequest:
    properties:
      avatar_url:
        type: string
      description:
        type: string
      max_participants:
        type: integer
      name:
        type: string
      official_site_url:
        type: string
      participation_format:
        $ref: '#/definitions/domain.RunParticipationFormat'
      permissions:
        $ref: '#/definitions/domain.RunPermissionsType'
      registration_until:
        type: string
      route:
        $ref: '#/definitions/domain.Route'
      run_id:
        type: integer
      start_place:
        $ref: '#/definitions/domain.Place'
      start_time:
        type: string
      transaction_id:
        type: string
    type: object
  domain.UpdateRunResponse:
    properties:
      run:
        $ref: '#/definitions/domain.Run'
    type: object
host: localhost:8080
info:
  contact: {}
  title: Forest Run API
  version: 0.0.1
paths:
  /api/runs/create:
    post:
      description: Create run
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.CreateRunRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CreateRunResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create run
      tags:
      - runs
  /api/runs/update:
    post:
      description: Update run
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateRunRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UpdateRunResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update run
      tags:
      - runs
  /api/subscribe:
    post:
      description: Start receiving notifications of user's actions
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Subscribe to user
      tags:
      - subscriptions
  /api/unsubscribe:
    post:
      description: Stop receiving notifications of user's actions
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Unsubscribe from user
      tags:
      - subscriptions
  /auth/refresh:
    post:
      description: Refresh JWT Tokens pair
      parameters:
      - description: Refresh tokens data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.RefreshTokensRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.RefreshTokensResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh Tokens
      tags:
      - auth
  /auth/sign-in:
    post:
      description: Log into app and get access tokens
      parameters:
      - description: SignIn data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Sign In
      tags:
      - auth
  /auth/sign-up:
    post:
      description: Register in app
      parameters:
      - description: SignUp data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Sign Up
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
