basePath: /
definitions:
  domain.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  domain.JWTTokenData:
    properties:
      expiresAt:
        type: string
      token:
        type: string
    type: object
  domain.RefreshTokensRequest:
    properties:
      refreshToken:
        type: string
    type: object
  domain.RefreshTokensResponse:
    properties:
      authToken:
        $ref: '#/definitions/domain.JWTTokenData'
      refreshToken:
        type: string
    type: object
  domain.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.SignInResponse:
    properties:
      authToken:
        $ref: '#/definitions/domain.JWTTokenData'
      refreshToken:
        type: string
    type: object
  domain.SignUpRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.SignUpResponse:
    type: object
  domain.SubscriptionRequest:
    properties:
      userId:
        type: integer
    type: object
  domain.SubscriptionResponse:
    type: object
host: localhost:8080
info:
  contact: {}
  title: Forest Run API
  version: 0.0.1
paths:
  /api/refresh:
    post:
      description: Refresh JWT Tokens pair
      parameters:
      - description: Refresh tokens data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.RefreshTokensRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.RefreshTokensResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh Tokens
      tags:
      - auth
  /api/subscribe:
    post:
      description: Start receiving notifications of user's actions
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Subscribe to user
      tags:
      - subscriptions
  /api/unsubscribe:
    post:
      description: Stop receiving notifications of user's actions
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Unsubscribe from user
      tags:
      - subscriptions
  /auth/sign-in:
    post:
      description: Log into app and get access tokens
      parameters:
      - description: SignIn data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Sign In
      tags:
      - auth
  /auth/sign-up:
    post:
      description: Register in app
      parameters:
      - description: SignUp data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Sign Up
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
