basePath: /
definitions:
  domain.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  domain.SignUpRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  domain.SignUpResponse:
    type: object
host: localhost:8080
info:
  contact: {}
  title: Forest Run API
  version: 0.0.1
paths:
  /auth/sign-up:
    post:
      description: Register in app and get access token
      parameters:
      - description: SignUp data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Sign Up
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
