name: forest-run

on:
  push:
    branches: [ "devops/workflow" ]
  pull_request:
    branches: [ "devops/workflow" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:


      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21' 


      - name: Build main project
        run: |
          pwd
          ls


      # - name: Build project
      #   run: go build -v ./realtime-runs-server


      - name: Commit and push if success
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Compiled Go project"
          git push origin HEAD:devops/workflow
        if: success() 

