name: forest-run

on:
  workflow_dispatch:

  push:
    branches: [ "devops/workflow" ]
  pull_request:
    branches: [ "devops/workflow" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21' 


      - name: Build main project
        run: |
          go build -v ./main-server


      - name: Build project
        run: go build -v ./realtime-runs-server

